spring:
  application:
    name: Spring-AI
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG